# OSEMN Exercises

In [127]:
%matplotlib inline
import pandas as pd
import numpy as np
import random as rd
import re
import json

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [10]:
rng = np.random.default_rng()
data = rng.integers(0, 100, 40).tolist()
print(data)
with open('simple_data.txt', 'w') as simple:
    print(data, file=simple)

[62, 97, 62, 43, 46, 55, 16, 48, 53, 78, 75, 46, 15, 20, 91, 36, 75, 90, 5, 64, 33, 38, 33, 53, 85, 66, 3, 49, 58, 12, 1, 56, 42, 64, 72, 47, 24, 52, 86, 40]


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [57]:
matrix = rng.integers(0,100,(5,5))
print(matrix)
# with open('data.txt', 'w'): pass # Create the empty file, useful to erase any previous attempt at doing some exercise
    
with open('data.txt', 'w') as datatext:
    print(matrix, file=datatext)

[[65 70 41 31 10]
 [ 8 86 41  6 92]
 [56 91 34 53 11]
 [32 54 49  3 63]
 [95 43 74 56 48]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [58]:
with open('data.txt', 'r+') as datatext:
    wa = re.sub('[\\[\\],]', '', datatext.read())
    datatext.seek(0)
    datatext.write(wa)
    datatext.truncate()  # Write overwrites on cursor position, there will be underflown characters in the stream.
# This command erase truncates at cursos position, 

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [158]:
with open('credit_card.dat', 'rb') as cred:
    lines = cred.readlines()
    crco = [[chr(int(lines[i][j:j+6], 2)) for j in range(0, len(lines[i])-2, 6)] for i in range(len(lines))]
    for i in range(len(crco)): print(crco[i])



['7', '6', '4', '8', ' ', '5', '6', '7', '3', ' ', '3', '7', '7', '5', ' ', '2', '2', '7', '1', '\n']
['3', '2', '5', '7', ' ', '8', '2', '4', '7', ' ', '3', '3', '5', '4', ' ', '2', '2', '6', '6', '\n']
['2', '7', '2', '2', ' ', '0', '0', '0', '1', ' ', '4', '0', '1', '1', ' ', '6', '6', '5', '2', '\n']
['0', '6', '6', '1', ' ', '3', '0', '6', '3', ' ', '3', '7', '4', '2', ' ', '3', '1', '5', '0', '\n']
['0', '4', '3', '2', ' ', '1', '6', '0', '8', ' ', '1', '4', '6', '2', ' ', '4', '7', '4', '2', '\n']
['5', '8', '2', '7', ' ', '2', '0', '2', '7', ' ', '8', '7', '8', '5', ' ', '7', '3', '0', '3', '\n']
['5', '7', '7', '4', ' ', '8', '5', '2', '8', ' ', '2', '0', '8', '7', ' ', '1', '1', '1', '7', '\n']
['8', '1', '4', '0', ' ', '1', '2', '1', '0', ' ', '6', '3', '5', '2', ' ', '2', '8', '4', '5', '\n']
['5', '7', '6', '4', ' ', '1', '1', '3', '3', ' ', '7', '3', '0', '1', ' ', '7', '1', '0', '0', '\n']
['6', '4', '5', '6', ' ', '1', '7', '3', '7', ' ', '4', '1', '2', '6', ' ', '6', '

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

In [154]:
user = json.load(open('user_data.json'))
expr = [i for i in user if i['CreditCardType'] == 'American Express']
with open('USA_Expr.csv', 'w') as USA:
    for i in expr:
        

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.